name: 'List Folders'
description: 'List folders under tas-apis'

inputs:
  folder-name:
    description: 'Selected folder(s) to execute tests'
    required: true
    default: ''

runs:
  using: 'node12'
  main: 'index.js'
