name: folder-selection-action

on:
  workflow_dispatch:
    inputs:
      folder-names:
        description: 'Select the folders to execute tests (use comma for multi-select)'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Create folders input JSON file
        run: |
          echo '{"folderNames": "${{ github.event.inputs.folder-names }}" }' > folders.json

      - name: Upload folder selection artifact
        uses: actions/upload-artifact@v2
        with:
          name: folder-selection
          path: folders.json
