name: CI

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select the environment
      boolean:
        type: boolean
        description: True or False
      folder-name:
        type: choice
        description: 'Select the folder to execute tests'
        options:
          - sgnum
          - Test2

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: greet
        run: | 
          echo "environment is ${{ github.event.inputs.environment }} / ${{ inputs.environment }}"
          echo "boolean is ${{ github.event.inputs.boolean }}" / ${{ inputs.boolean }} 
          echo "choice is ${{ github.event.inputs.folder-name }}" / ${{ inputs.folder-name }}
          
          
      - name: Run Tests
        run: |
                 
          
      - name: Run Tests
        run: |
          cd ./src
          npm install
          $env:FOLDER_NAME="${{ github.event.inputs.folder-name }}"
          $env:FOLDER_NAME="${{ github.event.inputs.folder-name }}"
          echo "FOLDER_NAME: $env:FOLDER_NAME"
          $env:FEATURE_PATH="./Features/tas-apis/$env:FOLDER_NAME/features"
          echo "FEATURE_PATH: $env:FEATURE_PATH"

          $featureFiles = @()
          foreach ($file in (Get-ChildItem -Path $env:FEATURE_PATH -Filter "*.feature" -Recurse)) {
            $featureFiles += $file.FullName
          }
          $env:FEATURE_FILES_STRING = $featureFiles -join ','
          echo "FEATURE_FILES_STRING: $env:FEATURE_FILES_STRING"

          # Run the tests only if there are feature files in the selected folder
          if (-not [string]::IsNullOrEmpty($env:FEATURE_FILES_STRING)) {
            npm run test $env:FEATURE_FILES_STRING
          } else {
            echo "No feature files found in the selected folder."
          }
