name: CI

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select the environment
      boolean:
        type: boolean
        description: True or False
      folder-name:
        type: select
        description: 'Select the folder to execute tests'
        options:
          - ""
        runs:
          using: 'node12'
          main: './.github/actions/list-folders/dist/index.js'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          repository: your/repo

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: List Folders
        id: list_folders
        run: ./.github/actions/list-folders

      - name: Show Folder Selection
        id: folder_selection
        run: |
          FOLDERS=$(echo "${{ steps.list_folders.outputs.folders }}")
          echo "::set-output name=selected_folder::$FOLDERS"

      - name: greet
        run: | 
          echo "environment is ${{ github.event.inputs.environment }} / ${{ inputs.environment }}"
          echo "boolean is ${{ github.event.inputs.boolean }}" / ${{ inputs.boolean }} 
          echo "choice is ${{ github.event.inputs.folder-name }}" / ${{ inputs.folder-name }}
