name: Run-tests-workflow

on:
  workflow_dispatch:
    inputs:
      folder-name:
        description: 'Select the folder to execute tests'
        required: true
        default: 'Choose a folder'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name:   Run Tests
        run: |
          cd ./src
          npm install
          npm run test ${{ env.FOLDER_TO_EXECUTE }}
