name: Run-tests-workflow

on:
  workflow_dispatch:
    inputs:
      folder-name:
        description: 'Select the folder to execute tests'
        required: true
        type: choice  # Set the input type to 'choice'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: List Folders
        id: list_folders
        run: |
          # Set an environment variable with the folder list
          FOLDERS=$(cd ./src/Features/tas-apis && ls -d */ | sed 's#/##')
          echo "FOLDERS=$FOLDERS" >> $GITHUB_ENV

      - name: Show Folder Selection
        id: folder_selection
        run: |
          # Get the environment variable and store it as an output
          echo "::set-output name=selected_folder::$FOLDERS"

      - name: Display Folder Selection
        run: |
          echo "Selected folder: ${{ github.event.inputs.folder-name }}"
          echo "::set-output name=selected_folder::${{ github.event.inputs.folder-name }}"

      - name: Run Tests
        run: |
          cd ./src
          npm install
          npm run test ${{ fromJson(steps.folder_selection.outputs.selected_folder) }}
