name: CI

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select the environment
      folder-name:
        type: choice
        description: 'Select the folder to execute tests'
        options:
          - sgnum
          - Test2
      nonreg:
        type: boolean
        description: Nonreg
      all-tests:
        type: boolean
        description: All Tests

jobs:
  build:
    runs-on: windows-latest

    steps:
      # ... (previous steps remain unchanged)

      - name: Run Tests
        run: |
          cd ./src
          npm install
           $env:FOLDER_NAME="${{ github.event.inputs.folder-name }}"
              echo "FOLDER_NAME: $env:FOLDER_NAME"
              $env:FEATURE_PATH="./src/Features/tas-apis/$env:FOLDER_NAME/features"
              echo "FEATURE_PATH: $env:FEATURE_PATH"

              $featureFiles = @()
              foreach ($file in (Get-ChildItem -Path $env:FEATURE_PATH -Filter "*.feature" -Recurse)) {
                $featureFiles += $file.FullName
              }

              $env:FEATURE_FILES_STRING = $featureFiles -join ','
              echo "FEATURE_FILES_STRING: $env:FEATURE_FILES_STRING"

              # Run the tests only if there are feature files in the selected folder
              if (-not [string]::IsNullOrEmpty($env:FEATURE_FILES_STRING)) {
                npm run test $env:FEATURE_FILES_STRING
              } else {
                echo "No feature files found in the selected folder."
              }
