name: CI

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select the environment
      folder-name:
        type: choice
        description: 'Select the folder to execute tests'
        options:
          - sgnum
          - Test2
      nonreg:
        type: boolean
        description: Nonreg
      all-tests:
        type: boolean
        description: All Tests

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Run Tests
        working-directory: ./src
        run: |
          npm install
          $env:FOLDER_NAME="${{ github.event.inputs.folder-name }}"
          $env:FEATURE_PATH="./Features/tas-apis/$env:FOLDER_NAME/features"
          $featureFiles = @()
          if ($false -eq $true) {
            $featureFiles = Get-ChildItem -Path $env:FEATURE_PATH -Filter "*.feature" -Recurse | ForEach-Object { $_.FullName -replace '\\', '/' } | Join-String ','
          } elseif ($true -eq $true) {
            $featureFiles = Get-ChildItem -Path $env:FEATURE_PATH -Filter "*.feature" -Recurse | ForEach-Object { $_.FullName -replace '\\', '/' } | ForEach-Object { if (Get-Content $_ | Select-String -Pattern '@Nonreg') { $_ } } | Join-String ','
          } else {
            echo "Please select either Nonreg or All Tests checkbox."
            exit 1
          }
  
          if (-not [string]::IsNullOrEmpty($featureFiles)) {
            npm run test $featureFiles
          } else {
            echo "No feature files found in the selected folder."
          }
