name: Run-tests-workflow

on:
  workflow_dispatch:
    inputs:
      folder-name:
        description: 'Select the folder(s) to execute tests'
        required: true

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: List Folders
        id: list_folders
        uses: ./.github/actions/list-folders
        with:
          folder-name: ${{ github.event.inputs.folder-name }}

      - name: Show Folder Selection
        run: |
          echo "Selected folder(s): ${{ fromJson(steps.list_folders.outputs.folders) }}"

      - name: Run Tests
        run: |
          cd ./src
          npm install
          npm run test ${{ fromJson(steps.list_folders.outputs.folders) }}
