name: Run-tests-workflow

on:
  workflow_dispatch:
    inputs:
      folder-name:
        description: 'Select the folder to execute tests'
        required: true
        type: choice  # Set the input type to 'choice'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: List Folders
        id: list_folders
        run: node ./.github/actions/list-folders.js
        continue-on-error: true  # Continue on error since the action may not be available on the first run

      - name: Show Folder Selection
        id: folder_selection
        run: |
          # Use echo to set the output as a JSON array
          echo "::set-output name=selected_folder::$(echo "${{ steps.list_folders.outputs.stdout }}" | jq -r '.[]')"

      - name: Display Folder Selection
        run: |
          echo "Selected folder: ${{ github.event.inputs.folder-name }}"
          echo "::set-output name=selected_folder::${{ github.event.inputs.folder-name }}"

      - name: Run Tests
        run: |
          cd ./src
          npm install
          npm run test ${{ fromJson(steps.folder_selection.outputs.selected_folder) }}
