on:
  workflow_dispatch:
  
jobs:
  test:
    runs-on: windows-latest
    environment: SIT

    steps:
     - name: Checkout Repository
       uses: actions/checkout@v3
     - name: Steup Node js
       uses: actions/setup-node@v3
       with:
         node-version: 18

     - name: Run tests
       env:
         HOST: ${{ secrets.HOST }}
         KEY: ${{ secrets.KEY }}
         SECRET: ${{ secrets.SECRET }}
       run: |
           cd ./src
           npm install
           npm run test:report
          
     - name: Export Cucumber Reports using Xray-action
       uses: mikepenz/xray-action@v2.4.5
       with: 
         username: ${{secrets.ID}}
         password: ${{secrets.API_KEY}}
         testFormat: "cucumber"
         testPaths: "**/reports/*.json"
         projectKey: "MD"
         testExecKey: "MD-3300"
