name: Run-tests-workflow

on:
  workflow_dispatch:
    inputs:
      folder-name:
        description: 'Select the folder to execute tests'
        required: true
        type: choice  # Set the input type to 'choice'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        folder-name: ['folder1', 'folder2', 'folder3'] # Add your folder names here

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Show Folder Selection
        id: folder_selection
        run: |
          # Get the folder name from the matrix strategy and store it as an output
          echo "::set-output name=selected_folder::${{ matrix.folder-name }}"

      - name: Display Folder Selection
        run: |
          echo "Selected folder: ${{ steps.folder_selection.outputs.selected_folder }}"

      - name: Run Tests
        run: |
          cd ./src
          npm install
          npm run test ${{ steps.folder_selection.outputs.selected_folder }}
