name: CI

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select the environment
      boolean:
        type: boolean
        description: True or False
      folder-name:
        type: choice
        description: 'Select the folder to execute tests'
        choices: ${{ steps.list_folders.outputs.folders }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: List Folders
        id: list_folders
        run: |
          cd ./src/Features/tas-apis
          FOLDERS=$(ls -d */ | sed 's#/##')
          echo "Folder list: $FOLDERS"
          echo "::set-output name=folders::$FOLDERS"

      - name: Show Folder Selection
        id: folder_selection
        run: |
          FOLDERS=$(echo ${{ steps.list_folders.outputs.folders }} | tr '\n' ',' | sed 's/,$//')
          echo "Selected folder: ${{ github.event.inputs.folder-name }}"
          echo "::set-output name=selected_folder::${{ github.event.inputs.folder-name }}"

      - name: greet
        run: | 
          echo "environment is ${{ github.event.inputs.environment }} / ${{ inputs.environment }}"
          echo "boolean is ${{ github.event.inputs.boolean }}" / ${{ inputs.boolean }} 
          echo "choice is ${{ github.event.inputs.folder-name }}" / ${{ inputs.choice }}
