name: CI

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select the environment
      boolean:
        type: boolean
        description: True or False
      folder-name:
        type: choice
        description: 'Select the folder to execute tests'
        options:
          - sgnum
          - Test2

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: greet
        run: | 
          echo "environment is ${{ github.event.inputs.environment }} / ${{ inputs.environment }}"
          echo "boolean is ${{ github.event.inputs.boolean }}" / ${{ inputs.boolean }} 
          echo "choice is ${{ github.event.inputs.folder-name }}" / ${{ inputs.folder-name }}
          
          
      - name: Run Tests
        run: |
          cd ./src
          npm install
          FOLDER_NAME="${{ github.event.inputs.folder-name }}"
          FEATURE_PATH="./Features/tas-apis/$FOLDER_NAME/features"
          FEATURE_FILES=$(find $FEATURE_PATH -type f -name "*.feature" -printf '%p,')
          FEATURE_FILES=${FEATURE_FILES%?}  # Remove the trailing comma

          # Run the tests only if there are feature files in the selected folder
          if [ -n "$FEATURE_FILES" ]; then
            npm run test $FEATURE_FILES
          else
            echo "No feature files found in the selected folder."
          fi
  
          
          
          
