name: Run-tests-workflow

on:
  workflow_dispatch:
    inputs:
      folder-names:
        description: 'Select the folders to execute tests'
        required: true
        type: string
        default: 'sgnum' # Default value to avoid error when no folder is selected

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Run Tests
        run: |
          # Convert the comma-separated list of folders to an array
          IFS=',' read -ra FOLDERS <<< "${{ github.event.inputs.folder-names }}"

          # Loop through the selected folders and execute tests
          for folder in "${FOLDERS[@]}"; do
            cd "./src/Features/tas-apis/${folder}"
            npm install
            npm run test
          done
