name: CI

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select the environment
      folder-name:
        type: choice
        description: 'Select the folder to execute tests'
        options:
          - sgnum
          - Test2
      nonreg:
        type: boolean
        description: Nonreg
      all-tests:
        type: boolean
        description: All Tests

jobs:
  build:
    runs-on: windows-latest

    steps:
      # ... (previous steps remain unchanged)

      - name: Run Tests
        run: |
          cd ./src
          npm install
          $env:FOLDER_NAME="${{ github.event.inputs.folder-name }}"
          $env:FEATURE_PATH="./Features/tas-apis/$env:FOLDER_NAME/features"
          $featureFiles = @()
          if (${{ github.event.inputs.all-tests }} -eq 'true') {
            Get-ChildItem -Path $env:FEATURE_PATH -Filter "*.feature" -Recurse | ForEach-Object { $featureFiles += $_.FullName }
          } elseif (${{ github.event.inputs.nonreg }} -eq 'true') {
            $featureFiles += (Get-ChildItem -Path $env:FEATURE_PATH -Filter "*.feature" -Recurse | ForEach-Object { $_.FullName } | Select-String -Pattern '@Nonreg').Matches | ForEach-Object { $_.Groups[0].Value }
          } else {
            Write-Host "Please select either Nonreg or All Tests checkbox."
            exit 1
          }
          $env:FEATURE_FILES_STRING = $featureFiles -join ','
          Write-Host "FEATURE_FILES_STRING: $env:FEATURE_FILES_STRING"

          if (-not [string]::IsNullOrEmpty($env:FEATURE_FILES_STRING)) {
            npm run test $env:FEATURE_FILES_STRING
          } else {
            Write-Host "No feature files found in the selected folder."
          }
