name: Run-tests-workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install actions/core
        run: npm install @actions/core

      - name: List Folders
        id: list_folders
        uses: ./.github/actions/list-folders
        with:
          folder-list: src/Features/tas-apis/*/

      - name: Select Folder
        id: folder_selection
        run: |
          echo "::set-output name=folder-selection::$INPUT_FOLDER_SELECTION"

        env:
          INPUT_FOLDER_SELECTION: ${{ fromJson(steps.list_folders.outputs.folder-selection) }}

      - name: Run Tests
        run: |
          cd ./src
          npm install
          npm run test ${{ env.INPUT_FOLDER_SELECTION }}
