name: Run-tests-workflow

on:
  workflow_dispatch:
    inputs:
      folder-name:
        description: 'Select the folder to execute tests'
        required: true
        type: choice
        options:
          - sgnum
          - sgnum2
          - sgnum3

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Dispatch Folder Selection
        id: dispatch_folder
        uses: ./dispatch-action
        with:
          folder_name: ${{ github.event.inputs.folder-name }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Tests
        run: |
          cd ./src/Features/tas-apis/${{ github.event.inputs.folder-name }}
          npm install
          npm run test
