name: Run-tests-workflow

on:
  workflow_dispatch:
    inputs:
      folder-name:
        description: 'Select the folder to execute tests'
        required: true

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: List Folders
        id: list_folders
        run: |
          cd ./src/Features/tas-apis
          $folders = Get-ChildItem -Directory | ForEach-Object { $_.Name }
          $folders -join ","
          echo "::set-output name=folders::$folders"

          
      - name: Show Folder Selection
        id: folder_selection
        run: |
          FOLDERS=$(echo ${{ steps.list_folders.outputs.folders }})
          FOLDER_LIST=(${FOLDERS// / })
          SELECTED_FOLDER=$(echo "::set-output name=selected_folder::{\"value\": \"${FOLDER_LIST[@]}\"}")

      - name: Display Folder Selection
        run: |
