name: CI

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select the environment
      folder-name:
        type: choice
        description: 'Select the folder to execute tests'
        options:
          - sgnum
          - Test2
      nonreg:
        type: boolean
        description: Nonreg
      all-tests:
        type: boolean
        description: All Tests

jobs:
  build:
    runs-on: windows-latest

    steps:
      # ... (previous steps remain unchanged)

      - name: Run Tests
        run: |
          cd ./src
          npm install
          FOLDER_NAME="${{ github.event.inputs.folder-name }}"
          FEATURE_PATH="./Features/tas-apis/$FOLDER_NAME/features"
          FEATURE_FILES=()
          if ${{ github.event.inputs.all-tests }} == true; then
            FEATURE_FILES=($(find $FEATURE_PATH -name "*.feature" -type f))
          elif ${{ github.event.inputs.nonreg }} == true; then
            FEATURE_FILES=($(grep -rl "@Nonreg" $FEATURE_PATH | tr '\n' ' '))
          else
            echo "Please select either Nonreg or All Tests checkbox."
            exit 1
          fi
          FEATURE_FILES_STRING=$(IFS=,; echo "${FEATURE_FILES[*]}")

          if [ -n "$FEATURE_FILES_STRING" ]; then
            npm run test $FEATURE_FILES_STRING
          else
            echo "No feature files found in the selected folder."
          fi
