name: CI

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select the environment
      folder-name:
        type: choice
        description: 'Select the folder to execute tests'
        options:
          - sgnum
          - Test2
      nonreg:
        type: boolean
        description: Nonreg
      all-tests:
        type: boolean
        description: All Tests

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: greet
        run: | 
          Write-Host "environment is ${{ github.event.inputs.environment }}"
          Write-Host "nonreg is ${{ github.event.inputs.nonreg }}"
          Write-Host "all-tests is ${{ github.event.inputs.all-tests }}"
          Write-Host "folder-name is ${{ github.event.inputs.folder-name }}"
          
      - name: Run Tests
        working-directory: ./src
        run: |
          npm install
          $env:FOLDER_NAME="${{ github.event.inputs.folder-name }}"
          Write-Host "FOLDER_NAME : $env:FOLDER_NAME"
          $env:FEATURE_PATH="./Features/tas-apis/$env:FOLDER_NAME/features"
          Write-Host "FEATURE_PATH : $env:FEATURE_PATH"
          
          # Create an empty array to store feature files
          $featureFiles = @()
          
          # Search for feature files based on checkbox selection
          if (${{ github.event.inputs.all-tests }} == true) {
