name: Run-tests-workflow

on:
  workflow_dispatch:
    inputs:
      folder-names:
        description: 'Select the folders to execute tests'
        required: true

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: List Folders
        id: list_folders
        run: |
          cd ./src/Features/tas-apis
          FOLDERS=$(ls -d */ | sed 's#/##')
          echo "Folder list: $FOLDERS"
          echo "::set-output name=folders::$FOLDERS"

      - name: Show Folder Selection
        id: folder_selection
        run: |
          FOLDERS=$(echo ${{ steps.list_folders.outputs.folders }} | tr '\n' ',' | sed 's/,$//')
          echo "Folder list for selection: $FOLDERS"
          echo "::set-output name=selected_folder::$FOLDERS"

      - name: Display Folder Selection
        run: |
          echo "Selected folders: ${{ github.event.inputs.folder-names }}"
          echo "::set-output name=selected_folder::${{ github.event.inputs.folder-names }}"
