name: Run-tests-workflow

on:
  workflow_dispatch:
    inputs:
      PARAMETERS:
        description: "A JSON object with folder list"
        required: true

jobs:
  myJob:
    name: "My job"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup inputs from json
        id: setup-inputs
        run: |
          # Read the JSON file and pass it as a JSON object to the workflow_dispatch popup
          INPUT_JSON=$(cat folders_config.json)
          echo "::set-output name=parameters::'$INPUT_JSON'"

      - name: Display Inputs
        run: |
          echo "Parameters: ${{ steps.setup-inputs.outputs.parameters }}"
          Write-Host "environment is ${{ github.event.inputs.environment }}"
          Write-Host "test-type is ${{ github.event.inputs.test-type }}"
          Write-Host "Selected folders: ${{ steps.read_folders.outputs.folders }}" 

      - name: Run Tests
        working-directory: ./src
        run: |
          npm install

          # Use split function to separate selected folders
          $selectedFolders = "${{ steps.read_folders.outputs.folders }}" -split ','

          Write-Host "Selected folders: $($selectedFolders -join ',')"
          Write-Host "Selected folders count: $($selectedFolders.Count)"

          $testType = "${{ github.event.inputs.test-type }}"

          foreach ($folder in $selectedFolders) {
            $env:FOLDER_NAME = $folder
            Write-Host "Running tests for folder: $env:FOLDER_NAME"
            $env:FEATURE_PATH = "./Features/tas-apis/$env:FOLDER_NAME/features"
            Write-Host "FEATURE_PATH: $env:FEATURE_PATH"

            # ... Rest of the script to run tests for each folder ...
          }

          Write-Host "All folders completed."
