name: Run Tests

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select the environment
      folder-names:
        type: string
        description: 'Select the folders to execute tests (use comma for multi-select)'
      test-type:
        type: choice
        description: 'Select the type of test'
        options:
          - Nonreg
          - All Tests

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Display Inputs
        run: |
          Write-Host "environment is ${{ github.event.inputs.environment }}"
          Write-Host "folder-names is ${{ github.event.inputs.folder-names }}"
          Write-Host "test-type is ${{ github.event.inputs.test-type }}"

      - name: Install http-server
        run: npm install -g http-server

      - name: Display checkboxes UI
        run: |
          mkdir -p .github/workflow-ui
          echo '<h2>Folder Selection</h2>' > .github/workflow-ui/index.html
          echo '<input type="checkbox" name="folder" value="folder1"> Folder 1<br>' >> .github/workflow-ui/index.html
          echo '<input type="checkbox" name="folder" value="folder2"> Folder 2<br>' >> .github/workflow-ui/index.html
          # Add more folders as needed

      - name: Run Tests
        if: startsWith(github.ref, 'refs/tags/') && github.event.inputs.test-type == 'All Tests'
        run: |
          npm install
          folders=$(http-server .github/workflow-ui -p 8000 -s -c-1 | grep "name=\"folder\"" | awk -F "\"" '{print $6}')
          for folder in $folders; do
            $env:FOLDER_NAME=$folder
            $env:FEATURE_PATH="./Features/tas-apis/$env:FOLDER_NAME/features"
            Write-Host "Running All Test Feature Files for folder: $env:FOLDER_NAME"
            # Add your test command here, for example:
            # npm run test $env:FEATURE_PATH/*.feature
          done
