name: Run Tests

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select the environment
      sgnum:
        type: boolean
        description: 'Select the sgnum folder'
      Test2:
        type: boolean
        description: 'Select the Test2 folder'
      test-type:
        type: choice
        description: 'Select the type of test'
        options:
          - Nonreg
          - All Tests

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Display Inputs
        run: |
          Write-Host "environment is ${{ github.event.inputs.environment }}"
          Write-Host "sgnum folder selected: ${{ github.event.inputs.sgnum }}"
          Write-Host "Test2 folder selected: ${{ github.event.inputs.Test2 }}"
          Write-Host "test-type is ${{ github.event.inputs.test-type }}"

      - name: Set up Folder Selection
        id: folder-selection
        run: |
          $selectedFolders = @()
          if ("${{ github.event.inputs.sgnum }}" -eq 'true') { $selectedFolders += "sgnum" }
          if ("${{ github.event.inputs.Test2 }}" -eq 'true') { $selectedFolders += "Test2" }
          Write-Host "Selected folders: $selectedFolders"
          Write-Output "selected_folders=$selectedFolders" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8
        shell: pwsh
      
      - name: Run Tests
        working-directory: ./src
        run: |
           npm install

                    # Read selected folders from the environment variable
                    $selectedFolders = $env:selected_folders -split ','

                    Write-Host "Selected folders: $selectedFolders"
                    Write-Host "Selected folders count: $($selectedFolders.Count)"

                    $testType = "${{ github.event.inputs.test-type }}"

                    foreach ($folder in $selectedFolders) {
                      $env:FOLDER_NAME = $folder
                      Write-Host "Running tests for folder: $env:FOLDER_NAME"
                      $env:FEATURE_PATH = "./Features/tas-apis/$env:FOLDER_NAME/features"
                      Write-Host "FEATURE_PATH: $env:FEATURE_PATH"

            # Check if the folder exists
            if (Test-Path -Path $env:FEATURE_PATH) {
              # Create an empty array to store feature files
              $featureFiles = @()

              # Search for feature files based on test type selection
              if ("${{ github.event.inputs.test-type }}" -eq 'All Tests') {
                Write-Host "Running All Test Feature Files"
                $featureFiles = Get-ChildItem -Path $env:FEATURE_PATH -Filter "*.feature" -Recurse | ForEach-Object { $_.FullName -replace '\\', '/' }
              }
              elseif ("${{ github.event.inputs.test-type }}" -eq 'Nonreg') {
                Write-Host "Running Nonreg Feature Files"
                $featureFiles = Get-ChildItem -Path $env:FEATURE_PATH -Filter "*.feature" -Recurse | ForEach-Object {
                  $content = Get-Content $_
                  if ($content -match '@nonreg') { $_.FullName -replace '\\', '/' }
                }
              } else {
                Write-Host "Please select a valid test type."
                exit 1
              }

            # Check if feature files were found and run the tests
              if ($featureFiles.Count -gt 0) {
                # Loop through the feature files and run the tests
                foreach ($file in $featureFiles) {
                  Write-Host "Running feature file: $file"
                  npm run test -- $file
                }
              } else {
                Write-Host "No feature files found for the selected test type in folder $folderName."
              }
            } else {
              Write-Host "Folder $folderName does not exist."
            }
          }
          Write-Host "All folders completed."
