name: run-tests

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select the environment
      test-type:
        type: choice
        description: 'Select the type of test'
        options:
          - Nonreg
          - All Tests

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Display Inputs
        run: |
          Write-Host "environment is ${{ github.event.inputs.environment }}"
          Write-Host "test-type is ${{ github.event.inputs.test-type }}"

      - name: Folder Selection
        id: folder_selection
        uses: ./.github/actions/folder-selection-action
        with:
          folder-names: 'sgnum,Test2'  # Replace with your available folder names separated by comma

      - name: Run Tests
        working-directory: ./src
        run: |
          npm install
          $selectedFolders = "${{ steps.folder_selection.outputs.selected-folders }}" -split ','

          # Loop through the selected folders and run the tests for each one
          foreach ($folderName in $selectedFolders) {
            $env:FOLDER_NAME = $folderName
            Write-Host "Running tests for folder: $folderName"
            $env:FEATURE_PATH = "./Features/tas-apis/$env:FOLDER_NAME/features"
            Write-Host "FEATURE_PATH : $env:FEATURE_PATH"

            # Add your logic to run the tests for each folder here
            # You can use the same logic you had in your previous script
          }

          Write-Host "All folders completed."
