name: CI

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select the environment
      folder-names:
        type: string
        description: 'Enter the folders to execute tests (use comma for multi-select)'
      test-type:
        type: choice
        description: 'Select the type of test'
        options:
          - Nonreg
          - All Tests

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Generate Folder Selection UI
        run: node ./.github/scripts/create-folder-selection-ui.js ${{ github.event.inputs.folder-names }}
        id: folder-selection

      - name: Display Inputs
        run: |
          Write-Host "environment is ${{ github.event.inputs.environment }}"
          Write-Host "folder-names is ${{ github.event.inputs.folder-names }}"
          Write-Host "test-type is ${{ github.event.inputs.test-type }}"

      - name: Display Folder Selection UI
        run: |
          $folderSelectionPath = '${{ steps.folder-selection.outputs.folder-selection-path }}'
          Write-Host "Click the link to access the Folder Selection UI:"
          Write-Host "file://$folderSelectionPath"

      - name: Run Tests
        if: ${{ github.event.inputs.folder-names != '' && steps.folder-selection.outputs.folder-selection-path != '' }}
        working-directory: ./src
        run: |
          npm install
          $folderNames = "${{ github.event.inputs.folder-names }}" -split ','

          foreach ($folderName in $folderNames) {
            $env:FOLDER_NAME = $folderName
            # ... (rest of the existing code to run tests for selected folders)
          }

          Write-Host "All folders completed."
