name: Run Tests

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select the environment
      sgnum:
        type: boolean
        description: 'Select sgnum folder'
      Test2:
        type: boolean
        description: 'Select Test2 folder'
      test-type:
        type: choice
        description: 'Select the type of test'
        options:
          - Nonreg
          - All Tests

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Set up Folder Selection
        id: folder-selection
        run: |
          selectedFolders=()
          if [ "${{ github.event.inputs.sgnum }}" = "true" ]; then
            selectedFolders+=("sgnum")
          fi
          if [ "${{ github.event.inputs.Test2 }}" = "true" ]; then
            selectedFolders+=("Test2")
          fi
          echo "selected-folders=${selectedFolders[*]}" >> $GITHUB_ENV
        shell: bash

      - name: Display Inputs
        run: |
          Write-Host "environment is ${{ github.event.inputs.environment }}"
          IFS=',' read -ra selectedFolders <<< "${{ env.selected_folders }}"
          for folder in "${selectedFolders[@]}"; do
            Write-Host "Selected folder: $folder"
          done

          $testType = "${{ github.event.inputs['test-type'] }}"
          Write-Host "Selected test type: $testType"


      - name: Display Inputs
        run: |
          Write-Host "environment is ${{ github.event.inputs.environment }}"
          $selectedFolders = Get-Content $env:GITHUB_ENV | ConvertFrom-StringData
          Write-Host "Selected folders: $selectedFolders"

          $testType = "${{ github.event.inputs['test-type'] }}"
          Write-Host "Selected test type: $testType"


      - name: Run Tests
        working-directory: ./src
        run: |
          $selectedFolders = Get-Content $env:GITHUB_ENV | ConvertFrom-StringData
          $testType = "${{ github.event.inputs.test-type }}"
          foreach ($folder in $selectedFolders.GetEnumerator()) {
            Write-Host "Running tests for folder: $folder"
            $env:FOLDER_NAME = $folder
            $env:FEATURE_PATH = "./Features/tas-apis/$env:FOLDER_NAME/features"
            Write-Host "FEATURE_PATH: $env:FEATURE_PATH"

            if ($testType -eq 'All Tests') {
              Write-Host "Running All Test Feature Files"
              $featureFiles = Get-ChildItem -Path $env:FEATURE_PATH -Filter "*.feature" -Recurse | ForEach-Object { $_.FullName -replace '\\', '/' }
            } elseif ($testType -eq 'Nonreg') {
              Write-Host "Running Nonreg Feature Files"
              $featureFiles = Get-ChildItem -Path $env:FEATURE_PATH -Filter "*.feature" -Recurse | ForEach-Object {
                $content = Get-Content $_
                if ($content -match '@nonreg') { $_.FullName -replace '\\', '/' }
              }
            } else {
              Write-Host "Please select a valid test type."
              exit 1
            }

            if ($featureFiles.Count -gt 0) {
              foreach ($file in $featureFiles) {
                Write-Host "Running feature file: $file"
                npm run test -- $file
              }
            } else {
              Write-Host "No feature files found for the selected test type in folder $env:FOLDER_NAME."
            }
          }

          Write-Host "All folders completed."
