name: run

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select the environment
      folder1:
        type: boolean
        description: 'Select Folder1'
      folder2:
        type: boolean
        description: 'Select Folder2'
      test-type:
        type: choice
        description: 'Select the type of test'
        options:
          - Nonreg
          - All Tests

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Display Inputs
        run: |
          Write-Host "environment is ${{ github.event.inputs.environment }}"
          Write-Host "folder1 is ${{ github.event.inputs.folder1 }}"
          Write-Host "folder2 is ${{ github.event.inputs.folder2 }}"
          Write-Host "test-type is ${{ github.event.inputs.test-type }}"

      - name: Install Dependencies
        run: npm install

     
