name: Run-tests-workflow
on:
  workflow_dispatch:
    inputs:
      folder-names:
      type: choice
      description: 'Select the folder(s) to execute tests'
      options:
        - test1
        - test2
        - test3
jobs:
  myJob:
    name: "My job"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install jq -y

      - name: Generate Dropdown Options
        id: generate-dropdown
        run: |
          node ./.github/actions/generate_dropdown.js
          echo "::set-output name=folder_options::$(cat options.json)"

      - name: Set Dropdown Options
        id: set-options
        run: |
          echo "OPTIONS=$(cat options.json)" >> $GITHUB_ENV

      - name: Display Inputs
        run: |
          echo "Dropdown options: ${{ env.OPTIONS }}"
          echo "Folder options: ${{ steps.generate-dropdown.outputs.folder_options }}"
