on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select the environment

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Read Config and Set Folders
        id: read-config
        run: |
          node ./.github/actions/read_config.js >> selected_folders.txt
        shell: pwsh

      # Add more steps for your build process as needed

      - name: Run Tests
        working-directory: ./src
        run: |
          # Read the selected folders from the file
          $selectedFolders = Get-Content selected_folders.txt
          Write-Host "Selected folders: $selectedFolders"
          # Use the selected folders or perform other actions based on the data
          # For example, you can use $selectedFolders in your test script
          # or run tests on the selected folders here
