name: Run Tests

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select the environment

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Read Config and Set Folders
        id: read-config
        run: |
          # Replace the command below with your custom script to read the JSON file and extract the selected folders
          # For example, you can use Node.js or Python script to read the JSON
          selectedFolders=$(node -e 'const config = require(".github/actions/folders_config.json"); const selectedFolders = config.folders.filter(folder => folder.selected).map(folder => folder.name); console.log(selectedFolders.join(","));')

          # Store the selected folders in the GITHUB_ENV
          echo "SELECTED_FOLDERS=$selectedFolders" >> $GITHUB_ENV

      # Add more steps for your build process as needed

      - name: Run Tests
        working-directory: ./src
        run: |
          # Access the selected folders from the GITHUB_ENV variable
          $selectedFolders = $env:SELECTED_FOLDERS
          Write-Host "Selected folders: $selectedFolders"
          # Use the selected folders or perform other actions based on the data
          # For example, you can use $selectedFolders in your test script
          # or run tests on the selected folders here
