name: Run-tests-workflow

on:
  workflow_dispatch:
    inputs:
      folder-names:
        description: 'Select the folder(s) to execute tests'
        required: true
        type: choice

jobs:
  myJob:
    name: "My job"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install jq -y

      - name: Generate Dropdown Options
        id: generate-dropdown
        run: |
          node ./.github/actions/generate_dropdown.js

      - name: Set Dropdown Options
        run: |
          echo "::set-env name=OPTIONS::$(cat options.json)"

      - name: Display Inputs
        run: |
          echo "Dropdown options: ${{ env.OPTIONS }}"
